field: 989f6b5c-82cf-4a15-aa85-fe9b821cee4b
fieldLayouts:
  24d10f0a-7220-46c7-98d2-4c0818d07dbe:
    tabs:
      -
        elements:
          -
            fieldUid: a8d65c69-c832-4301-902e-712b8221762f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a8d65c69-c832-4301-902e-712b8221762f:
    contentColumnType: string
    fieldGroup: null
    handle: audio
    instructions: 'Upload an audio file.'
    name: Audio
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:d9c51571-b4e8-40c9-abaf-dab181ce75bf'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an audio file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:25e8c49e-de76-4f02-b0f2-4412c37bdad4'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:d9c51571-b4e8-40c9-abaf-dab181ce75bf'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: audio
name: Audio
sortOrder: 7
