field: 989f6b5c-82cf-4a15-aa85-fe9b821cee4b
fieldLayouts:
  d0e70e63-9251-4b8e-8944-f31af538c0e1:
    tabs:
      -
        elements:
          -
            fieldUid: 16dcf610-573a-409e-b404-c4aafe8ea764
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19d67a4c-90d7-4ae3-a367-e59f631af8d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  16dcf610-573a-409e-b404-c4aafe8ea764:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Limit of eight.'
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:85402e79-b5f4-49d2-b19b-4210804143c7'
      defaultUploadLocationSubpath: ''
      limit: '8'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:85402e79-b5f4-49d2-b19b-4210804143c7'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:85402e79-b5f4-49d2-b19b-4210804143c7'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  19d67a4c-90d7-4ae3-a367-e59f631af8d7:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Describe this image/these images.'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: images
name: Images
sortOrder: 5
