field: 989f6b5c-82cf-4a15-aa85-fe9b821cee4b
fieldLayouts:
  9db008b5-5d2f-4947-a621-566114dc4116:
    tabs:
      -
        elements:
          -
            fieldUid: d5d7809c-23f4-4811-aac0-88ea44885cf1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: fb9a7b57-e9d1-46d4-b1ee-aa8038caa57a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: bbaa68dc-df36-42aa-a667-b5ee4f79fd6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  bbaa68dc-df36-42aa-a667-b5ee4f79fd6a:
    contentColumnType: string
    fieldGroup: null
    handle: posterImage
    instructions: ''
    name: 'Poster image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:85402e79-b5f4-49d2-b19b-4210804143c7'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:25e8c49e-de76-4f02-b0f2-4412c37bdad4'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:85402e79-b5f4-49d2-b19b-4210804143c7'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d5d7809c-23f4-4811-aac0-88ea44885cf1:
    contentColumnType: string
    fieldGroup: null
    handle: mp4
    instructions: 'Upload an MP4 video file.'
    name: MP4
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:696a96fe-981a-49b3-8947-b85b4ec0dc06'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an MP4 file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:696a96fe-981a-49b3-8947-b85b4ec0dc06'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:696a96fe-981a-49b3-8947-b85b4ec0dc06'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fb9a7b57-e9d1-46d4-b1ee-aa8038caa57a:
    contentColumnType: string
    fieldGroup: null
    handle: webm
    instructions: 'Upload a WebM video file.'
    name: WebM
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:696a96fe-981a-49b3-8947-b85b4ec0dc06'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add a WebM file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:25e8c49e-de76-4f02-b0f2-4412c37bdad4'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:696a96fe-981a-49b3-8947-b85b4ec0dc06'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: Video
sortOrder: 5
