fieldLayouts:
  a0754d49-f7b1-4b97-a267-f594af39a360:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 989f6b5c-82cf-4a15-aa85-fe9b821cee4b # Page components
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 65332953-fec0-4f58-b96d-8297c3994640
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Options
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 4394a157-7f1e-4e52-afc7-ea0def9e88e8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: standardContent
hasTitleField: true
name: 'Standard content'
section: 3a95c5ae-691b-45a9-af63-804ec4f32d8f
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
