contentColumnType: text
fieldGroup: be866704-e9e5-489a-94b0-c7763eec7317
handle: quote
instructions: 'Note: do not add speech marks, these are handled in the template.'
name: Quote
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
