dateModified: 1600514996
email:
  fromEmail: hello@jaycollett.co
  fromName: JayCraft
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: ''
      auto_inject: '1'
      decline: Decline
      defer_js: ''
      disable_in_live_preview: '1'
      dismiss: Accept
      dismiss_on_scroll: '0'
      dismiss_on_timeout: '0'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '365'
      honour_do_not_track_header: ''
      layout: classic
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: whitegreen
      palette_banner: '#efefef'
      palette_banner_text: '#404040'
      palette_button: '#8ec760'
      palette_button_text: '#ffffff'
      palette_left_button_bg: '#8ec760'
      palette_left_button_text: '#ffffff'
      palette_link: '#ffffff'
      position: bottom-left
      preload_css: ''
      revokable: ''
      secure_only: ''
      target: _blank
      type: info
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.7
    settings:
      originalNavHash:
        __assoc__:
          -
            - acd97fb0-d20d-4ccb-a137-17698687e2d1
            - W3sibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJkYXNoYm9hcmQiLCJmb250SWNvbiI6ImdhdWdlIn0seyJsYWJlbCI6IkVudHJpZXMiLCJ1cmwiOiJlbnRyaWVzIiwiZm9udEljb24iOiJzZWN0aW9uIn0seyJsYWJlbCI6Ikdsb2JhbHMiLCJ1cmwiOiJnbG9iYWxzIiwiZm9udEljb24iOiJnbG9iZSJ9LHsibGFiZWwiOiJUYWdzIiwidXJsIjoidGFncyIsImljb24iOiIvVXNlcnMvamF5Y29sbGV0dC9TaXRlcy9qYXljb2xsZXR0L2pheWNyYWZ0L3ZlbmRvci9ldGhlci90YWdzL3NyYy9pY29uLW1hc2suc3ZnIiwiaWQiOiJ0YWctbWFuYWdlciJ9LHsibGFiZWwiOiJBc3NldHMiLCJ1cmwiOiJhc3NldHMiLCJmb250SWNvbiI6ImFzc2V0cyJ9LHsibGFiZWwiOiJTRU8iLCJ1cmwiOiJzZW8iLCJpY29uIjoiL1VzZXJzL2pheWNvbGxldHQvU2l0ZXMvamF5Y29sbGV0dC9qYXljcmFmdC92ZW5kb3IvZXRoZXIvc2VvL3NyYy9pY29uLW1hc2suc3ZnIiwic3VibmF2Ijp7ImRhc2hib2FyZCI6eyJsYWJlbCI6IkRhc2hib2FyZCIsInVybCI6InNlbyJ9LCJzaXRlbWFwIjp7ImxhYmVsIjoiU2l0ZW1hcCIsInVybCI6InNlby9zaXRlbWFwIn0sInJlZGlyZWN0cyI6eyJsYWJlbCI6IlJlZGlyZWN0cyIsInVybCI6InNlby9yZWRpcmVjdHMifSwic2V0dGluZ3MiOnsibGFiZWwiOiJTZXR0aW5ncyIsInVybCI6InNlby9zZXR0aW5ncyJ9fX0seyJ1cmwiOiJ1dGlsaXRpZXMiLCJsYWJlbCI6IlV0aWxpdGllcyIsImZvbnRJY29uIjoidG9vbCIsImJhZGdlQ291bnQiOjB9LHsidXJsIjoic2V0dGluZ3MiLCJsYWJlbCI6IlNldHRpbmdzIiwiZm9udEljb24iOiJzZXR0aW5ncyJ9LHsidXJsIjoicGx1Z2luLXN0b3JlIiwibGFiZWwiOiJQbHVnaW4gU3RvcmUiLCJmb250SWNvbiI6InBsdWdpbiJ9XQ==
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.1
    settings:
      description: '{pageDescription|striptags}'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  similar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  slug-alert:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      alertMessage: 'Changing a slug can have a potentially negative effect on your site''s SEO and any bookmarked links. Create a redirect after changing a slug, or don''t change the slug at all.'
      pluginIsActive: '1'
  snitch:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: JayCraft
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
