fieldLayouts:
  8762c3d1-6cfc-4a3a-9590-3e15f33414e7:
    tabs:
      -
        elements:
          -
            fieldUid: 4a8ef1e9-0d62-4ea2-b094-f78aa2d8b906
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb3be2e2-4f29-4954-867d-c4ab5dc55a9c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Business details'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c32ae7fc-8956-4f92-a0c3-9d6560441ccd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4caee081-e90b-4ece-8d4a-8d67ab5b2928
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social media'
        sortOrder: 2
handle: siteDetails
name: 'Site details'
