currLabel: 'Plugin Store'
customIcon: null
enabled: '1'
handle: plugin-store
icon: plugin
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: '0'
order: 11
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: '0'
url: plugin-store
