currLabel: Assets
customIcon: ''
enabled: true
handle: divider
icon: ''
layout: 84a829e7-98fe-429f-9ab4-33e75d521955 # Default
newWindow: false
order: 7
prevLabel: Divider
prevUrl: ''
type: divider
url: ''
