currLabel: Tags
customIcon: null
enabled: '1'
handle: tags
icon: /Users/jaycollett/Sites/jaycollett/jaycraft/vendor/ether/tags/src/icon-mask.svg
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: '0'
order: 3
prevLabel: Tags
prevUrl: tags
type: '0'
url: tags
