currLabel: Utilities
customIcon: null
enabled: '1'
handle: utilities
icon: tool
layout: eaecba95-0830-4740-9f54-bd68ef3c6896
newWindow: '0'
order: '7'
prevLabel: Utilities
prevUrl: utilities
type: '0'
url: utilities
