defaultPlacement: end
enableVersioning: true
handle: site
name: Site
propagationMethod: all
siteSettings:
  734c8496-7eca-4f66-8377-dba7854a48eb: # JayCraft
    enabledByDefault: true
    hasUrls: true
    template: site/_index.twig
    uriFormat: '{parentUri}/{slug}'
structure:
  maxLevels: null
  uid: 33ddf800-f394-4193-8e7e-263151808a1a
type: structure
